import type { ChallengeModule, ChallengeStep, ChargeConfig } from '@/lib/challenge-modules'

export const CONNECT_STARTING_BALANCE_CENTS = 500_000 // AUD $5,000

export const CONNECT_CHALLENGE_MODULES: ChallengeModule[] = [
  {
    number: 1,
    id: 'create_connected_account',
    title: 'Create Your First Connected Account',
    tagline: 'Set up an Express connected account and walk through Stripe\'s hosted onboarding.',
    difficulty: 'Beginner',
    expectedCharges: 0,
    maxExposureCents: 0,
    chargeConfig: [],
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'What you\'re building',
        content: 'In this first task, you\'ll create an Express connected account using the Stripe API and walk through the hosted onboarding flow. Express accounts are the most common account type for platforms because Stripe handles the compliance and KYC burden while you control the onboarding entry point. By the end of this task, you\'ll have a connected account visible in your Dashboard with capabilities requested. This is the foundation for everything that follows.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Open the Connect section',
        instruction: 'Open your Stripe Dashboard and navigate to **Connect > Accounts**. Right now it should be empty or show only test accounts. This is where your connected accounts will appear after creation.',
        dashboardLink: '/connect/accounts',
        checkboxLabel: 'I have the Connect accounts page open',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Create an Express account via API',
        instruction: 'Using the Stripe API (via the Dashboard API playground, CLI, or your own code), create an Express connected account. Set `type: "express"`, request capabilities for `card_payments` and `transfers`, and include an email address. Note the account ID (starts with `acct_`) from the response. You\'ll need it for every subsequent task.\n\nExample API call:\n```\nstripe accounts create \\\n  --type=express \\\n  -d "capabilities[card_payments][requested]"=true \\\n  -d "capabilities[transfers][requested]"=true \\\n  -d email="freelancer@example.com"\n```',
        checkboxLabel: 'I have created an Express account and noted the account ID',
      },
      {
        stepNumber: 4,
        type: 'action',
        title: 'Generate an Account Link and complete onboarding',
        instruction: 'Generate an Account Link for your new account with `type: "account_onboarding"`. Set a `return_url` and `refresh_url` (these can be any URL in test mode, like `http://localhost:3000/onboarding/complete`). Open the resulting URL in your browser and walk through Stripe\'s hosted onboarding using test data. Use the test SSN last four `0000` for instant verification.\n\nExample:\n```\nstripe account_links create \\\n  --account=acct_YOUR_ACCOUNT_ID \\\n  -d type=account_onboarding \\\n  -d "return_url"="http://localhost:3000/return" \\\n  -d "refresh_url"="http://localhost:3000/refresh"\n```',
        checkboxLabel: 'I have completed the hosted onboarding flow',
      },
      {
        stepNumber: 5,
        type: 'verify',
        title: 'Verify your connected account',
        instruction: 'Go back to **Connect > Accounts** in your Dashboard and confirm your new account appears. Check its capability status and requirements.',
        dashboardLink: '/connect/accounts',
        checklist: [
          'Connected account ID is visible in the Dashboard Connect section',
          'Account status shows capabilities as pending or active',
          'Business details from the test onboarding are populated',
          'No items remain in currently_due requirements (after test verification)',
        ],
      },
    ],
  },
  {
    number: 2,
    id: 'destination_charge',
    title: 'Process a Charge with Platform Fee',
    tagline: 'Create a destination charge with a 10% platform fee and watch money flow to both accounts.',
    difficulty: 'Intermediate',
    expectedCharges: 1,
    maxExposureCents: 10000,
    chargeConfig: [{ count: 1, amountMinCents: 10000, amountMaxCents: 10000, metadata: { type: 'destination_charge', task: 'platform_fee' } }],
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'How destination charges work',
        content: 'A destination charge is created on your platform account with a specified connected account as the destination. The charge amount hits your platform\'s balance first, then Stripe automatically creates a Transfer to the connected account. You specify an application_fee_amount to keep a portion as your platform revenue. For this task, you\'ll create a $100 charge with a 10% ($10) platform fee, meaning $90 flows to the connected account.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Create a PaymentIntent with destination and fee',
        instruction: 'Create a PaymentIntent on your platform account with the following parameters:\n- `amount: 10000` (that\'s $100.00 in cents)\n- `currency: "usd"`\n- `transfer_data[destination]`: your connected account ID from Task 1\n- `application_fee_amount: 1000` (that\'s $10.00, your 10% platform fee)\n\nExample:\n```\nstripe payment_intents create \\\n  --amount=10000 \\\n  --currency=usd \\\n  -d "transfer_data[destination]"=acct_YOUR_ACCOUNT_ID \\\n  -d application_fee_amount=1000\n```\n\nNote the PaymentIntent ID from the response.',
        checkboxLabel: 'I have created a PaymentIntent with destination and application fee',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Confirm the charge with a test card',
        instruction: 'Confirm the PaymentIntent using the test card `4242424242424242` with any future expiration date and any CVC. You can do this via the API or the Dashboard. If using the API:\n```\nstripe payment_intents confirm pi_YOUR_PAYMENT_INTENT_ID \\\n  -d "payment_method_data[type]"=card \\\n  -d "payment_method_data[card][number]"=4242424242424242 \\\n  -d "payment_method_data[card][exp_month]"=12 \\\n  -d "payment_method_data[card][exp_year]"=2026 \\\n  -d "payment_method_data[card][cvc]"=123\n```',
        checkboxLabel: 'I have confirmed the charge with a test card',
      },
      {
        stepNumber: 4,
        type: 'action',
        title: 'Check the platform balance',
        instruction: 'Navigate to **Dashboard > Balance** on your platform account. You should see the $10.00 application fee credited to your platform balance. Then navigate to **Connect > Accounts**, click on your connected account, and check its balance. It should show $90.00 (minus Stripe processing fees).',
        dashboardLink: '/balance/overview',
        checkboxLabel: 'I can see the application fee in my platform balance',
      },
      {
        stepNumber: 5,
        type: 'verify',
        title: 'Verify the fee split',
        instruction: 'Confirm the money flowed correctly by checking both the platform and connected account balances in the Dashboard.',
        checklist: [
          'PaymentIntent shows succeeded status',
          'Platform balance shows the $10.00 application fee credit',
          'Connected account balance shows the net amount after fee and processing',
          'A Transfer object is visible linking the charge to the connected account',
        ],
      },
    ],
  },
  {
    number: 3,
    id: 'webhook_handler',
    title: 'Implement Your Webhook Handler',
    tagline: 'Set up a Connect webhook endpoint and handle account, payout, and payment events.',
    difficulty: 'Intermediate',
    expectedCharges: 0,
    maxExposureCents: 0,
    chargeConfig: [],
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'How Connect webhooks differ',
        content: 'Connect webhooks are different from standard Stripe webhooks. When you create a webhook endpoint with `connect: true`, it receives events from all connected accounts, not just your platform. Each event includes an `account` field that tells you which connected account generated it. Your handler needs to read this field and route the event to the right context in your system. This is the foundation of event-driven architecture for any Connect platform.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Start the Stripe CLI listener',
        instruction: 'Open a terminal and start the Stripe CLI to forward Connect events to your local endpoint:\n```\nstripe listen --forward-connect-to localhost:3000/webhook\n```\nNote: this forwards connected account events. For platform events, you\'d use `--forward-to`. In development, run both. The CLI will print a webhook signing secret (starts with `whsec_`). You\'ll need this to verify event signatures.',
        checkboxLabel: 'I have the Stripe CLI listener running with --forward-connect-to',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Build your webhook endpoint',
        instruction: 'Create a `/webhook` endpoint in your application that:\n1. Verifies the webhook signature using the signing secret from the CLI\n2. Parses the event type from `event.type`\n3. Extracts the connected account ID from `event.account`\n4. Handles these event types:\n   - `account.updated`: log the capability changes (check `data.object.capabilities`)\n   - `payout.paid`: log the payout amount and destination account\n   - `payout.failed`: log the `failure_code` and affected account\n5. Returns a 200 status code for all handled events\n\nMake sure your handler is idempotent. Check `event.id` against a set of processed events before taking action.',
        checkboxLabel: 'I have built a webhook handler for the three event types',
      },
      {
        stepNumber: 4,
        type: 'action',
        title: 'Trigger an account.updated event',
        instruction: 'Update your connected account to trigger an `account.updated` event. You can do this by updating the account\'s metadata:\n```\nstripe accounts update acct_YOUR_ACCOUNT_ID \\\n  -d "metadata[test_key]"="test_value"\n```\nWatch your webhook handler logs to confirm the event arrived and was processed correctly. Check that `event.account` matches your connected account ID.',
        checkboxLabel: 'I have triggered and received an account.updated event',
      },
      {
        stepNumber: 5,
        type: 'verify',
        title: 'Verify webhook handling',
        instruction: 'Confirm your webhook handler is working correctly for all three event types.',
        checklist: [
          'Webhook endpoint returns 200 for account.updated events',
          'Handler logs the account ID from event.account correctly',
          'Handler differentiates between event types and routes to the right logic',
          'Event signature verification is in place (using whsec_ secret)',
        ],
      },
    ],
  },
  {
    number: 4,
    id: 'manual_payout',
    title: 'Trigger and Verify a Payout',
    tagline: 'Switch to manual payouts, trigger one via API, then deliberately cause a failure.',
    difficulty: 'Advanced',
    expectedCharges: 0,
    maxExposureCents: 0,
    chargeConfig: [],
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'Why manual payouts matter',
        content: 'Most Connect platforms start with automatic payouts, where Stripe sends funds to the connected account\'s bank on a daily schedule. But for escrow models, dispute hold periods, or platforms that want explicit control over when money moves, manual payouts are essential. With manual payouts, funds accumulate in the connected account\'s Stripe balance until your platform explicitly triggers a payout via the API. This gives you maximum control over fund flow timing.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Switch to manual payout schedule',
        instruction: 'Update your connected account to use a manual payout schedule:\n```\nstripe accounts update acct_YOUR_ACCOUNT_ID \\\n  -d "settings[payouts][schedule][interval]"=manual\n```\nThis tells Stripe to hold funds in the connected account\'s balance until you explicitly create a payout.',
        checkboxLabel: 'I have switched the connected account to manual payouts',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Create a manual payout',
        instruction: 'Trigger a manual payout to the connected account\'s test bank account. You\'ll need to use the Stripe-Account header to act as the connected account:\n```\nstripe payouts create \\\n  --amount=5000 \\\n  --currency=usd \\\n  --stripe-account=acct_YOUR_ACCOUNT_ID\n```\nThis creates a $50.00 payout from the connected account\'s Stripe balance to their test bank account. Watch your webhook handler for the `payout.paid` event.',
        checkboxLabel: 'I have created a manual payout and received the payout.paid event',
      },
      {
        stepNumber: 4,
        type: 'action',
        title: 'Trigger a payout failure',
        instruction: 'Now deliberately trigger a payout failure. Update the connected account\'s external bank account to use the test routing number that returns an `account_closed` failure. In test mode, you can create a new external account with the failure-triggering test bank details, then attempt another payout. Watch your webhook handler for the `payout.failed` event and verify it logs the `failure_code`.\n\nThe test bank account number `000000000001` with routing `110000000` will succeed. To trigger a failure, use the account number that Stripe\'s test docs specify for the desired failure mode.',
        checkboxLabel: 'I have triggered a payout failure and logged the failure_code',
        warningText: 'Payout failures in production mean a connected account didn\'t receive their money. Your handler should immediately notify both your operations team and the affected account.',
      },
      {
        stepNumber: 5,
        type: 'verify',
        title: 'Verify payout handling',
        instruction: 'Confirm your payout workflow handles both success and failure paths.',
        checklist: [
          'Connected account payout schedule is set to manual',
          'Manual payout was created and payout.paid event was received',
          'Payout failure was triggered and failure_code was logged by the handler',
          'Webhook handler differentiates between payout.paid and payout.failed events',
        ],
      },
    ],
  },
  {
    number: 5,
    id: 'capability_requirement',
    title: 'Handle a Capability Requirement',
    tagline: 'Simulate an outstanding requirement and build a re-onboarding flow.',
    difficulty: 'Advanced',
    expectedCharges: 0,
    maxExposureCents: 0,
    chargeConfig: [],
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'The requirements lifecycle',
        content: 'Connected accounts don\'t stay verified forever. Regulatory changes, document expiry, or business changes can trigger new requirements at any time. When this happens, Stripe sends an `account.updated` event with items in the `requirements.currently_due` array. Your platform needs to detect this, notify the account owner, and provide a path back into the onboarding flow. Platforms that don\'t handle this will see capabilities degrade and payouts fail without warning.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Simulate an outstanding requirement',
        instruction: 'In test mode, you can simulate outstanding requirements by requesting a new capability or using Stripe\'s test helpers. One approach is to request a capability that requires additional information:\n```\nstripe accounts update acct_YOUR_ACCOUNT_ID \\\n  -d "capabilities[us_bank_account_ach_payments][requested]"=true\n```\nThis may trigger new requirements. Alternatively, check the account\'s current `requirements.currently_due` and `requirements.eventually_due` arrays. Watch your webhook handler for the `account.updated` event.',
        checkboxLabel: 'I have triggered new requirements on the connected account',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Inspect the account.updated event',
        instruction: 'Look at the `account.updated` event in your webhook handler logs. Inspect the `data.object.requirements` section of the payload. Note which fields appear in `currently_due` and `eventually_due`. These are the specific pieces of information Stripe needs from the account owner before the capability can become active.',
        checkboxLabel: 'I have inspected the requirements in the account.updated payload',
      },
      {
        stepNumber: 4,
        type: 'action',
        title: 'Generate a re-onboarding Account Link',
        instruction: 'Build a function (or run the API call manually) that reads `requirements.currently_due` from the event payload and generates a new Account Link for the connected account to complete the outstanding requirements:\n```\nstripe account_links create \\\n  --account=acct_YOUR_ACCOUNT_ID \\\n  -d type=account_onboarding \\\n  -d "return_url"="http://localhost:3000/onboarding/complete" \\\n  -d "refresh_url"="http://localhost:3000/onboarding/refresh"\n```\nIn production, you\'d send this URL to the account owner via email or surface it in your platform UI.',
        checkboxLabel: 'I have generated a new Account Link for re-onboarding',
      },
      {
        stepNumber: 5,
        type: 'verify',
        title: 'Verify the re-onboarding flow',
        instruction: 'Confirm your requirement handling pipeline works end to end.',
        checklist: [
          'account.updated event was processed with non-empty currently_due array',
          'Handler correctly extracted the specific required fields',
          'New Account Link was generated for the connected account',
          'Re-onboarding URL is logged or could be sent to the account owner',
        ],
      },
    ],
  },
  {
    number: 6,
    id: 'split_payout',
    title: 'Separate Charges and Transfers with Split Payout',
    tagline: 'Split a single charge between two connected accounts using separate charges and transfers.',
    difficulty: 'Expert',
    expectedCharges: 1,
    maxExposureCents: 20000,
    chargeConfig: [{ count: 1, amountMinCents: 20000, amountMaxCents: 20000, metadata: { type: 'split_charge', task: 'multi_party_split' } }],
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'Why separate charges and transfers exist',
        content: 'Sometimes a single payment needs to be split between multiple recipients. Destination charges only support one destination, so they can\'t handle this. Separate charges and transfers decouple the charge from the fund movement entirely. You create a charge on your platform, then create individual Transfer objects to each connected account at any time. This pattern is essential for collaborative marketplaces, multi-vendor orders, or any scenario where one payment funds multiple parties.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Create a second connected account',
        instruction: 'Create a second Express connected account to act as the "collaborator." Follow the same process from Task 1:\n```\nstripe accounts create \\\n  --type=express \\\n  -d "capabilities[card_payments][requested]"=true \\\n  -d "capabilities[transfers][requested]"=true \\\n  -d email="collaborator@example.com"\n```\nThen generate an Account Link and complete the onboarding with test data. Note this second account ID.',
        checkboxLabel: 'I have created and onboarded a second connected account',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Create a charge on the platform',
        instruction: 'Create a PaymentIntent on your platform account (no destination this time) for $200.00:\n```\nstripe payment_intents create \\\n  --amount=20000 \\\n  --currency=usd\n```\nConfirm it with the test card `4242424242424242`. Note the charge ID from the response (starts with `ch_` or find it via the PaymentIntent\'s `latest_charge` field).',
        checkboxLabel: 'I have created and confirmed a $200 charge on the platform',
      },
      {
        stepNumber: 4,
        type: 'action',
        title: 'Transfer 70% to the primary seller',
        instruction: 'Create a Transfer of $140.00 (70%) to your first connected account, referencing the original charge:\n```\nstripe transfers create \\\n  --amount=14000 \\\n  --currency=usd \\\n  -d destination=acct_FIRST_ACCOUNT_ID \\\n  -d source_transaction=ch_YOUR_CHARGE_ID\n```\nThe `source_transaction` parameter links this transfer to the original charge for reconciliation.',
        checkboxLabel: 'I have transferred 70% to the primary seller',
      },
      {
        stepNumber: 5,
        type: 'action',
        title: 'Transfer 30% to the collaborator',
        instruction: 'Create a second Transfer of $60.00 (30%) to your second connected account, also referencing the same charge:\n```\nstripe transfers create \\\n  --amount=6000 \\\n  --currency=usd \\\n  -d destination=acct_SECOND_ACCOUNT_ID \\\n  -d source_transaction=ch_YOUR_CHARGE_ID\n```\nYour platform retains the remaining amount (minus Stripe fees) as implicit revenue.',
        checkboxLabel: 'I have transferred 30% to the collaborator',
      },
      {
        stepNumber: 6,
        type: 'verify',
        title: 'Verify the split',
        instruction: 'Confirm the multi-party split worked correctly by checking all three account balances.',
        checklist: [
          'Two connected accounts exist and are active',
          'Single $200 charge was created on the platform account',
          'Transfer to primary seller is $140.00 (70%)',
          'Transfer to collaborator is $60.00 (30%)',
          'Both transfers reference the original charge via source_transaction',
          'Connected account balances reflect the correct amounts',
        ],
      },
    ],
  },
]
