export type StepType = 'read' | 'action' | 'rule' | 'verify' | 'fire'
export type ChallengeStep = {
  stepNumber: number
  type: StepType
  title: string
  content?: string
  instruction?: string
  dashboardLink?: string
  checkboxLabel?: string
  ruleCode?: string
  ruleExplanation?: string
  checklist?: string[]
  fireTitle?: string
  fireDescription?: string
  expectedCharges?: number
  warningText?: string
}
export type ChallengeModule = {
  number: number
  id: string
  title: string
  tagline: string
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert'
  expectedCharges: number
  maxExposureCents: number
  steps: ChallengeStep[]
  chargeConfig: { count: number; amountMinCents: number; amountMaxCents: number; testCard?: string; metadata: Record<string, string>; sameCard?: boolean }[]
}

export const BILLING_STARTING_BALANCE_CENTS = 500_000

export const BILLING_CHALLENGE_MODULES: ChallengeModule[] = [
  {
    number: 1,
    id: 'create-products-prices',
    title: 'Create Products & Prices',
    tagline: 'Set up your product catalog with recurring prices',
    difficulty: 'Beginner',
    expectedCharges: 5,
    maxExposureCents: 25_000,
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'Understand the Product-Price Model',
        content: 'In Stripe Billing, a Product represents what you sell and a Price defines how much and how often to charge. A single Product can have multiple Prices (monthly, yearly, different currencies). You will create products with both recurring and one-time prices.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Create a SaaS Product',
        instruction: 'Go to the Products page and create a new product called "Pro Plan" with a monthly recurring price of $29.00 and a yearly recurring price of $290.00.',
        dashboardLink: 'https://dashboard.stripe.com/test/products/create',
        checkboxLabel: 'I created the Pro Plan product with monthly and yearly prices',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Create a Metered Product',
        instruction: 'Create another product called "API Calls" with a metered usage-based price of $0.01 per unit. Set the billing scheme to "per_unit" and usage aggregation to "sum".',
        dashboardLink: 'https://dashboard.stripe.com/test/products/create',
        checkboxLabel: 'I created the API Calls product with metered pricing',
      },
      {
        stepNumber: 4,
        type: 'verify',
        title: 'Verify Your Product Catalog',
        instruction: 'Navigate to your Products list and confirm you have at least 2 products with 3 total prices.',
        dashboardLink: 'https://dashboard.stripe.com/test/products',
        checklist: [
          'Pro Plan product exists with monthly ($29) and yearly ($290) prices',
          'API Calls product exists with metered pricing ($0.01/unit)',
          'All prices are in test mode',
        ],
      },
      {
        stepNumber: 5,
        type: 'fire',
        title: 'Simulate Product Catalog Usage',
        fireTitle: 'Catalog Charge Simulation',
        fireDescription: 'Simulating initial subscription charges against your product catalog to validate pricing configuration.',
        expectedCharges: 5,
        warningText: 'This will create 5 test charges using your configured prices.',
      },
    ],
    chargeConfig: [
      {
        count: 3,
        amountMinCents: 2900,
        amountMaxCents: 2900,
        testCard: '4242424242424242',
        metadata: { module: 'products-prices', type: 'monthly_subscription' },
        sameCard: true,
      },
      {
        count: 2,
        amountMinCents: 29000,
        amountMaxCents: 29000,
        testCard: '4242424242424242',
        metadata: { module: 'products-prices', type: 'yearly_subscription' },
        sameCard: true,
      },
    ],
  },
  {
    number: 2,
    id: 'first-subscription',
    title: 'Your First Subscription',
    tagline: 'Create and manage a live recurring subscription',
    difficulty: 'Beginner',
    expectedCharges: 10,
    maxExposureCents: 50_000,
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'Subscription Basics',
        content: 'A Subscription connects a Customer to one or more Prices on a recurring schedule. When created, Stripe automatically generates an Invoice and attempts payment. The subscription moves through statuses: incomplete → active → past_due → canceled.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Create a Test Customer',
        instruction: 'Create a new customer with a test email. Then attach the test card 4242 4242 4242 4242 as their default payment method.',
        dashboardLink: 'https://dashboard.stripe.com/test/customers/create',
        checkboxLabel: 'I created a customer with a payment method attached',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Create a Subscription',
        instruction: 'Navigate to your customer and create a new subscription using your Pro Plan monthly price ($29/month). Ensure "charge automatically" is selected as the collection method.',
        dashboardLink: 'https://dashboard.stripe.com/test/subscriptions/create',
        checkboxLabel: 'I created an active subscription for my customer',
      },
      {
        stepNumber: 4,
        type: 'verify',
        title: 'Verify Subscription is Active',
        instruction: 'Check that the subscription status is "active" and an invoice was created and paid.',
        dashboardLink: 'https://dashboard.stripe.com/test/subscriptions',
        checklist: [
          'Subscription status shows "Active"',
          'An invoice was generated and marked as "Paid"',
          'A successful payment appears in the Payments list',
        ],
      },
      {
        stepNumber: 5,
        type: 'action',
        title: 'Update the Subscription',
        instruction: 'Upgrade the subscription from monthly to yearly pricing. Observe how Stripe handles proration by generating a credit for unused monthly time and charging the yearly amount.',
        dashboardLink: 'https://dashboard.stripe.com/test/subscriptions',
        checkboxLabel: 'I upgraded the subscription and see the proration invoice',
      },
      {
        stepNumber: 6,
        type: 'fire',
        title: 'Simulate Subscription Billing Cycles',
        fireTitle: 'Recurring Charge Simulation',
        fireDescription: 'Simulating multiple billing cycles to test subscription payment collection and invoice generation.',
        expectedCharges: 10,
        warningText: 'This will create 10 test charges simulating recurring billing cycles.',
      },
    ],
    chargeConfig: [
      {
        count: 7,
        amountMinCents: 2900,
        amountMaxCents: 2900,
        testCard: '4242424242424242',
        metadata: { module: 'first-subscription', type: 'recurring_monthly' },
        sameCard: true,
      },
      {
        count: 3,
        amountMinCents: 29000,
        amountMaxCents: 29000,
        testCard: '4242424242424242',
        metadata: { module: 'first-subscription', type: 'recurring_yearly' },
        sameCard: true,
      },
    ],
  },
  {
    number: 3,
    id: 'trial-and-coupons',
    title: 'Trial & Coupons',
    tagline: 'Offer free trials and apply discount coupons',
    difficulty: 'Intermediate',
    expectedCharges: 10,
    maxExposureCents: 40_000,
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'Trials and Discounts',
        content: 'Free trials delay the first charge until trial_end. Coupons reduce the invoice amount by a fixed amount or percentage. Promotion codes are customer-facing codes that apply coupons. You can combine trials with coupons for powerful acquisition offers.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Create a Coupon',
        instruction: 'Create a coupon that gives 50% off for the first 3 months. Set duration to "repeating" with duration_in_months=3.',
        dashboardLink: 'https://dashboard.stripe.com/test/coupons/create',
        checkboxLabel: 'I created a 50% off repeating coupon',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Create a Subscription with Trial',
        instruction: 'Create a new subscription with a 14-day free trial. Use trial_period_days=14. Attach the coupon you created so after the trial, the customer gets 50% off for 3 months.',
        dashboardLink: 'https://dashboard.stripe.com/test/subscriptions/create',
        checkboxLabel: 'I created a subscription with both a trial and coupon applied',
      },
      {
        stepNumber: 4,
        type: 'verify',
        title: 'Verify Trial Configuration',
        instruction: 'Confirm the subscription shows "trialing" status with the correct trial end date and the coupon is attached.',
        dashboardLink: 'https://dashboard.stripe.com/test/subscriptions',
        checklist: [
          'Subscription status is "Trialing"',
          'Trial end date is 14 days from creation',
          'Coupon shows as applied (50% off, 3 months)',
          'No invoice has been charged yet',
        ],
      },
      {
        stepNumber: 5,
        type: 'action',
        title: 'Create a Promotion Code',
        instruction: 'Create a promotion code "WELCOME50" linked to your coupon. Set it to be active with a max redemption limit of 100.',
        dashboardLink: 'https://dashboard.stripe.com/test/coupons',
        checkboxLabel: 'I created the WELCOME50 promotion code',
      },
      {
        stepNumber: 6,
        type: 'fire',
        title: 'Simulate Post-Trial Charges',
        fireTitle: 'Trial Conversion Simulation',
        fireDescription: 'Simulating charges that occur after trial periods end, including discounted amounts from applied coupons.',
        expectedCharges: 10,
        warningText: 'This will create 10 test charges simulating post-trial billing with coupon discounts.',
      },
    ],
    chargeConfig: [
      {
        count: 6,
        amountMinCents: 1450,
        amountMaxCents: 1450,
        testCard: '4242424242424242',
        metadata: { module: 'trial-coupons', type: 'discounted_monthly' },
        sameCard: true,
      },
      {
        count: 4,
        amountMinCents: 2900,
        amountMaxCents: 2900,
        testCard: '4242424242424242',
        metadata: { module: 'trial-coupons', type: 'full_price_monthly' },
        sameCard: true,
      },
    ],
  },
  {
    number: 4,
    id: 'customer-portal-setup',
    title: 'Customer Portal Setup',
    tagline: 'Enable self-service billing management for customers',
    difficulty: 'Intermediate',
    expectedCharges: 15,
    maxExposureCents: 75_000,
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'Customer Portal Overview',
        content: 'The Stripe Customer Portal is a pre-built, hosted UI where customers can manage subscriptions, update payment methods, view invoices, and cancel plans. You configure available actions in the Portal Settings, then create portal sessions via the API to redirect customers.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Configure Portal Settings',
        instruction: 'Go to the Customer Portal settings and enable: update payment methods, view invoice history, cancel subscriptions (at period end), and switch plans between your monthly and yearly prices.',
        dashboardLink: 'https://dashboard.stripe.com/test/settings/billing/portal',
        checkboxLabel: 'I configured the Customer Portal with plan switching and cancellation',
      },
      {
        stepNumber: 3,
        type: 'rule',
        title: 'Portal Proration Rule',
        ruleCode: 'proration_behavior: always_invoice',
        ruleExplanation: 'When customers switch plans via the portal, Stripe prorates the change. Setting proration_behavior to "always_invoice" means the customer is immediately charged or credited the difference, rather than waiting until the next cycle.',
      },
      {
        stepNumber: 4,
        type: 'action',
        title: 'Test a Plan Switch',
        instruction: 'Using a test customer with an active monthly subscription, simulate an upgrade to the yearly plan. Verify that a proration invoice is generated showing the credit for unused monthly time and the new yearly charge.',
        dashboardLink: 'https://dashboard.stripe.com/test/subscriptions',
        checkboxLabel: 'I verified proration works when switching plans',
      },
      {
        stepNumber: 5,
        type: 'verify',
        title: 'Verify Portal Functionality',
        instruction: 'Confirm all portal features are working correctly.',
        dashboardLink: 'https://dashboard.stripe.com/test/settings/billing/portal',
        checklist: [
          'Payment method update is enabled',
          'Invoice history is visible',
          'Plan switching is configured with correct prices',
          'Cancellation is set to "at period end"',
          'Proration is set to "always invoice"',
        ],
      },
      {
        stepNumber: 6,
        type: 'fire',
        title: 'Simulate Portal Activity',
        fireTitle: 'Portal Usage Simulation',
        fireDescription: 'Simulating charges from plan switches, proration invoices, and renewal cycles triggered through the customer portal.',
        expectedCharges: 15,
        warningText: 'This will create 15 test charges simulating portal-driven plan changes and renewals.',
      },
    ],
    chargeConfig: [
      {
        count: 5,
        amountMinCents: 2900,
        amountMaxCents: 2900,
        testCard: '4242424242424242',
        metadata: { module: 'customer-portal', type: 'monthly_renewal' },
        sameCard: true,
      },
      {
        count: 5,
        amountMinCents: 26100,
        amountMaxCents: 26100,
        testCard: '4242424242424242',
        metadata: { module: 'customer-portal', type: 'proration_upgrade' },
        sameCard: true,
      },
      {
        count: 5,
        amountMinCents: 29000,
        amountMaxCents: 29000,
        testCard: '4242424242424242',
        metadata: { module: 'customer-portal', type: 'yearly_renewal' },
        sameCard: true,
      },
    ],
  },
  {
    number: 5,
    id: 'handle-failed-payments',
    title: 'Handle Failed Payments',
    tagline: 'Configure dunning and recover failed subscription payments',
    difficulty: 'Advanced',
    expectedCharges: 20,
    maxExposureCents: 100_000,
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'Understanding Payment Failures',
        content: 'Payment failures are inevitable in subscription billing—cards expire, have insufficient funds, or are flagged by banks. Stripe provides Smart Retries (ML-based retry timing), configurable retry schedules, customer emails, and webhooks to help you handle failures gracefully and recover revenue.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Configure Smart Retries',
        instruction: 'Go to Billing settings and enable Smart Retries. Configure the retry schedule to attempt up to 4 retries. Set the failed payment email to notify customers after the first failure.',
        dashboardLink: 'https://dashboard.stripe.com/test/settings/billing/automatic',
        checkboxLabel: 'I enabled Smart Retries with 4 retry attempts and customer emails',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Set Dunning End Behavior',
        instruction: 'Configure what happens when all retry attempts are exhausted. Set the subscription to be canceled after the final retry fails. Enable the "subscription canceled" email to notify the customer.',
        dashboardLink: 'https://dashboard.stripe.com/test/settings/billing/automatic',
        checkboxLabel: 'I configured end-of-dunning to cancel the subscription',
      },
      {
        stepNumber: 4,
        type: 'action',
        title: 'Test with Declining Card',
        instruction: 'Create a subscription using test card 4000000000000341 (attaches successfully but fails on charge). Observe the subscription entering "past_due" status and the retry schedule beginning.',
        dashboardLink: 'https://dashboard.stripe.com/test/subscriptions/create',
        checkboxLabel: 'I tested a subscription with a declining card and saw past_due status',
      },
      {
        stepNumber: 5,
        type: 'verify',
        title: 'Verify Dunning Configuration',
        instruction: 'Confirm your dunning workflow is properly configured.',
        dashboardLink: 'https://dashboard.stripe.com/test/settings/billing/automatic',
        checklist: [
          'Smart Retries is enabled',
          'Retry schedule has 4 attempts configured',
          'Failed payment email is enabled',
          'End-of-dunning action is set to "Cancel subscription"',
          'Test subscription shows "Past due" status',
        ],
      },
      {
        stepNumber: 6,
        type: 'fire',
        title: 'Simulate Payment Failures & Recovery',
        fireTitle: 'Dunning Simulation',
        fireDescription: 'Simulating a mix of successful and failed payment attempts to test your dunning configuration and Smart Retries behavior.',
        expectedCharges: 20,
        warningText: 'This will create 20 test charges—some will intentionally fail to simulate the dunning process.',
      },
    ],
    chargeConfig: [
      {
        count: 12,
        amountMinCents: 2900,
        amountMaxCents: 2900,
        testCard: '4242424242424242',
        metadata: { module: 'failed-payments', type: 'successful_retry' },
        sameCard: true,
      },
      {
        count: 5,
        amountMinCents: 2900,
        amountMaxCents: 2900,
        testCard: '4000000000000341',
        metadata: { module: 'failed-payments', type: 'declined_charge' },
        sameCard: true,
      },
      {
        count: 3,
        amountMinCents: 2900,
        amountMaxCents: 2900,
        testCard: '4000000000000069',
        metadata: { module: 'failed-payments', type: 'expired_card' },
        sameCard: true,
      },
    ],
  },
  {
    number: 6,
    id: 'full-billing-system',
    title: 'Full Billing System',
    tagline: 'Combine all elements into a production-ready billing flow',
    difficulty: 'Expert',
    expectedCharges: 25,
    maxExposureCents: 150_000,
    steps: [
      {
        stepNumber: 1,
        type: 'read',
        title: 'Production Billing Architecture',
        content: 'A production billing system combines products & prices, subscription management, the customer portal, dunning, webhooks, and analytics. Key webhooks to handle: invoice.payment_succeeded, invoice.payment_failed, customer.subscription.updated, and customer.subscription.deleted. You should also monitor MRR, churn, and recovery rates.',
      },
      {
        stepNumber: 2,
        type: 'action',
        title: 'Set Up Webhook Endpoints',
        instruction: 'Add a webhook endpoint (or use the Stripe CLI) to listen for billing events: invoice.payment_succeeded, invoice.payment_failed, customer.subscription.created, customer.subscription.updated, and customer.subscription.deleted.',
        dashboardLink: 'https://dashboard.stripe.com/test/webhooks/create',
        checkboxLabel: 'I configured a webhook endpoint for billing events',
      },
      {
        stepNumber: 3,
        type: 'action',
        title: 'Create a Multi-Tier Product Catalog',
        instruction: 'Create three products: "Starter" ($9/mo), "Pro" ($29/mo), and "Enterprise" ($99/mo). Each should have both monthly and yearly prices (yearly at 2 months free discount).',
        dashboardLink: 'https://dashboard.stripe.com/test/products/create',
        checkboxLabel: 'I created Starter, Pro, and Enterprise products with monthly and yearly prices',
      },
      {
        stepNumber: 4,
        type: 'action',
        title: 'Configure Complete Portal',
        instruction: 'Update your Customer Portal to allow switching between all three tiers (Starter, Pro, Enterprise) in both monthly and yearly intervals. Enable cancellation at period end and payment method updates.',
        dashboardLink: 'https://dashboard.stripe.com/test/settings/billing/portal',
        checkboxLabel: 'I configured the portal with all plan switching options',
      },
      {
        stepNumber: 5,
        type: 'action',
        title: 'End-to-End Subscription Test',
        instruction: 'Create a customer, subscribe them to the Starter plan, upgrade to Pro via the portal, then test a payment failure scenario with card 4000000000000341. Verify each webhook event fires correctly.',
        dashboardLink: 'https://dashboard.stripe.com/test/subscriptions/create',
        checkboxLabel: 'I completed the full lifecycle test: create → upgrade → payment failure',
      },
      {
        stepNumber: 6,
        type: 'verify',
        title: 'Verify Complete System',
        instruction: 'Review your full billing system configuration.',
        dashboardLink: 'https://dashboard.stripe.com/test/billing',
        checklist: [
          'Three-tier product catalog with monthly/yearly prices',
          'Customer Portal allows plan switching between all tiers',
          'Smart Retries and dunning configured',
          'Webhook endpoint receiving billing events',
          'Successful end-to-end lifecycle test (create → upgrade → failure handling)',
        ],
      },
      {
        stepNumber: 7,
        type: 'fire',
        title: 'Full System Load Test',
        fireTitle: 'Production Billing Simulation',
        fireDescription: 'Simulating a realistic mix of subscription charges across all tiers, including upgrades, renewals, and payment failures to stress-test your complete billing system.',
        expectedCharges: 25,
        warningText: 'This will create 25 test charges across all subscription tiers with some intentional failures.',
      },
    ],
    chargeConfig: [
      {
        count: 8,
        amountMinCents: 900,
        amountMaxCents: 900,
        testCard: '4242424242424242',
        metadata: { module: 'full-billing', type: 'starter_monthly' },
        sameCard: true,
      },
      {
        count: 6,
        amountMinCents: 2900,
        amountMaxCents: 2900,
        testCard: '4242424242424242',
        metadata: { module: 'full-billing', type: 'pro_monthly' },
        sameCard: true,
      },
      {
        count: 4,
        amountMinCents: 9900,
        amountMaxCents: 9900,
        testCard: '4242424242424242',
        metadata: { module: 'full-billing', type: 'enterprise_monthly' },
        sameCard: true,
      },
      {
        count: 4,
        amountMinCents: 2900,
        amountMaxCents: 2900,
        testCard: '4000000000000341',
        metadata: { module: 'full-billing', type: 'failed_renewal' },
        sameCard: true,
      },
      {
        count: 3,
        amountMinCents: 29000,
        amountMaxCents: 29000,
        testCard: '4242424242424242',
        metadata: { module: 'full-billing', type: 'pro_yearly' },
        sameCard: true,
      },
    ],
  },
]
